window.ReportingCenter = createDataTablePage({
  idPrefix: 'reporting',
  containerId: 'reporting-center',
  title: 'Reporting Center',
  description: 'Generate and export executive reports',
  viewType: 'list',
  columns: ['Report Title', 'Type', 'Format', 'Status', 'Generated By', 'Date', 'Actions'],
  actions: [
    { id: 'btn-refresh-reports', label: 'Refresh', icon: '🔄' },
    { id: 'btn-new-report', label: 'New Report', icon: '📄', primary: true }
  ],
  stats: [
    { label: 'Generated This Month', value: '24' },
    { label: 'Scheduled Reports', value: '5', color: 'var(--color-primary)' }
  ],
  endpoint: '/reports-center',
  emptyMessage: 'No Reports Available',
  emptyIcon: '📋',
  renderRow: function(m) {
    return `
      <tr>
        <td><strong>${m.title || ''}</strong></td>
        <td><span class="badge badge-outline">${m.type || ''}</span></td>
        <td><span class="badge badge-ghost">${(m.format || '').toUpperCase()}</span></td>
        <td><span class="badge badge-${m.status === 'completed' ? 'success' : 'warning'}">${m.status || ''}</span></td>
        <td>${m.created_by || ''}</td>
        <td>${m.created_at ? new Date(m.created_at).toLocaleString() : ''}</td>
        <td>
          ${m.status === 'completed' ? `<button class="btn btn-sm btn-outline" ${m.file_url ? `onclick="window.open('${m.file_url}')"` : ''}>Download</button>` : `<span class="loading loading-spinner loading-sm"></span>`}
        </td>
      </tr>
    `;
  },
  bindEvents: function() {
    const btnRefresh = document.getElementById('btn-refresh-reports');
    if (btnRefresh) {
      btnRefresh.addEventListener('click', () => {
        btnRefresh.classList.add('loading');
        setTimeout(() => {
          btnRefresh.classList.remove('loading');
          this.loadData();
        }, 800);
      });
    }

    const btnNew = document.getElementById('btn-new-report');
    if (btnNew) {
      btnNew.addEventListener('click', () => alert('Report generation modal would open here (stub)'));
    }
  }
});
