const ReportingCenter = {
  init() {
    this.container = document.getElementById('reporting-center');
    if (!this.container) return;
    this.render();
    this.bindEvents();
    this.loadData();
  },

  render() {
    this.container.innerHTML = `
      <div class="reporting-container fade-in">
        <div class="reporting-header">
          <div>
            <h2>Reporting Center</h2>
            <p class="text-muted">Generate and export executive reports</p>
          </div>
          <div class="reporting-actions">
            <button class="btn btn-outline" id="btn-refresh-reports">
              <span class="icon">🔄</span> Refresh
            </button>
            <button class="btn btn-primary" id="btn-new-report">
              <span class="icon">📄</span> New Report
            </button>
          </div>
        </div>

        <div class="reporting-stats">
          <div class="stat-card">
            <div class="stat-title">Generated This Month</div>
            <div class="stat-value">24</div>
          </div>
          <div class="stat-card">
            <div class="stat-title">Scheduled Reports</div>
            <div class="stat-value text-primary">5</div>
          </div>
        </div>

        <div class="reporting-list">
          <div class="table-container">
            <table class="table">
              <thead>
                <tr>
                  <th>Report Title</th>
                  <th>Type</th>
                  <th>Format</th>
                  <th>Status</th>
                  <th>Generated By</th>
                  <th>Date</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody id="reporting-tbody">
                <tr><td colspan="7" class="text-center">Loading...</td></tr>
              </tbody>
            </table>
          </div>
        </div>

        <!-- New Report Modal -->
        <div class="report-modal" id="new-report-modal" style="display:none;">
          <div class="report-modal-content">
            <div class="report-modal-header">
              <h3>Generate New Report</h3>
              <button class="btn btn-ghost btn-sm" id="btn-close-report">✕</button>
            </div>
            <div class="report-modal-body">
              <div class="form-control">
                <label>Report Title</label>
                <input type="text" class="input input-bordered" id="report-title" placeholder="e.g. Q3 Cost Analysis">
              </div>
              <div class="form-control">
                <label>Report Type</label>
                <select class="select select-bordered" id="report-type">
                  <option value="operational">Operational</option>
                  <option value="security">Security</option>
                  <option value="compliance">Compliance</option>
                  <option value="cost">Cost</option>
                  <option value="incident">Incident</option>
                </select>
              </div>
              <div class="form-control">
                <label>Format</label>
                <select class="select select-bordered" id="report-format">
                  <option value="pdf">PDF</option>
                  <option value="excel">Excel</option>
                  <option value="csv">CSV</option>
                </select>
              </div>
            </div>
            <div class="report-modal-footer">
              <button class="btn btn-outline" id="btn-cancel-report">Cancel</button>
              <button class="btn btn-primary" id="btn-generate-report">Generate</button>
            </div>
          </div>
        </div>

      </div>
    `;
  },

  bindEvents() {
    const btnRefresh = document.getElementById('btn-refresh-reports');
    if (btnRefresh) {
      btnRefresh.addEventListener('click', () => {
        btnRefresh.classList.add('loading');
        setTimeout(() => {
          btnRefresh.classList.remove('loading');
          this.loadData();
        }, 800);
      });
    }

    const modal = document.getElementById('new-report-modal');
    document.getElementById('btn-new-report')?.addEventListener('click', () => modal.style.display = 'flex');
    document.getElementById('btn-close-report')?.addEventListener('click', () => modal.style.display = 'none');
    document.getElementById('btn-cancel-report')?.addEventListener('click', () => modal.style.display = 'none');
    
    const btnGen = document.getElementById('btn-generate-report');
    if (btnGen) {
      btnGen.addEventListener('click', () => {
        alert('Report generation started. It will be available shortly.');
        modal.style.display = 'none';
        this.loadData();
      });
    }
  },

  async loadData() {
    try {
      const res = await fetch('/api/v1/reports-center');
      if (res.ok) {
        const json = await res.json();
        const items = json.data || [];
        this.renderTable(items);
        return;
      }
    } catch (e) {
      console.error('Reports API request failed:', e);
    }
    this.renderTable([]);
  },

  renderTable(data) {
    const tbody = document.getElementById('reporting-tbody');
    if (!tbody) return;

    if (!data || data.length === 0) {
      tbody.innerHTML = `
        <tr>
          <td colspan="7" style="text-align:center;color:var(--color-muted);padding:var(--space-lg);">
            <div style="font-size:36px;margin-bottom:var(--space-sm);">📋</div>
            <h4 style="margin:0;font-weight:600;">No Reports Available</h4>
            <p style="font-size:12px;margin:4px 0 0;">Create a new report to get started.</p>
          </td>
        </tr>
      `;
      return;
    }

    tbody.innerHTML = data.map(m => `
      <tr>
        <td><strong>${m.title || ''}</strong></td>
        <td><span class="badge badge-outline">${m.type || ''}</span></td>
        <td><span class="badge badge-ghost">${(m.format || '').toUpperCase()}</span></td>
        <td><span class="badge badge-${m.status === 'completed' ? 'success' : 'warning'}">${m.status || ''}</span></td>
        <td>${m.created_by || ''}</td>
        <td>${m.created_at ? new Date(m.created_at).toLocaleString() : ''}</td>
        <td>
          ${m.status === 'completed' ? `<button class="btn btn-sm btn-outline" ${m.file_url ? `onclick="window.open('${m.file_url}')"` : ''}>Download</button>` : `<span class="loading loading-spinner loading-sm"></span>`}
        </td>
      </tr>
    `).join('');
  }
};

window.ReportingCenter = ReportingCenter;
