<template>
  <!-- STEP 2: TOTP 6-digit Code -->
  <form
    v-if="mode === 'totp'"
    class="login-form step-panel"
    @submit.prevent="$emit('submitTotp')"
  >
    <div class="step-header">
      <div class="step-icon">🔐</div>
      <h2 class="step-title">Two-Factor Authentication</h2>
      <p class="step-subtitle">
        Enter the 6-digit verification code generated by your Google Authenticator or TOTP app.
      </p>
    </div>

    <div class="form-group">
      <label for="totp-code" class="form-label">6-Digit Security Code</label>
      <div class="totp-input-container">
        <input
          id="totp-code"
          ref="totpInput"
          :value="totpCode"
          type="text"
          inputmode="numeric"
          pattern="[0-9]*"
          maxlength="6"
          required
          autocomplete="one-time-code"
          placeholder="000000"
          class="input-glass form-input totp-input"
          :disabled="loading"
          @input="handleTotpInput"
        />
      </div>
    </div>

    <button
      type="submit"
      class="btn btn-primary login-btn"
      :disabled="loading || totpCode.length !== 6"
    >
      <span v-if="loading" class="spinner"></span>
      <span>{{ loading ? 'Verifying...' : 'Verify Code' }}</span>
    </button>

    <div class="auth-switch-links">
      <button type="button" class="text-link-btn" @click="$emit('switchToRecovery')">
        🔑 Use Recovery Code Instead
      </button>
      <button type="button" class="text-link-btn back-btn" @click="$emit('back')">
        ← Back to Sign In
      </button>
    </div>
  </form>

  <!-- STEP 2b: Recovery Code -->
  <form
    v-else-if="mode === 'recovery'"
    class="login-form step-panel"
    @submit.prevent="$emit('submitRecovery')"
  >
    <div class="step-header">
      <div class="step-icon">🔑</div>
      <h2 class="step-title">Recovery Code</h2>
      <p class="step-subtitle">
        Enter one of your 8-character backup emergency recovery codes.
      </p>
    </div>

    <div class="form-group">
      <label for="recovery-code" class="form-label">Backup Recovery Code</label>
      <input
        id="recovery-code"
        ref="recoveryInput"
        :value="recoveryCode"
        type="text"
        required
        placeholder="ABCD1234"
        class="input-glass form-input recovery-input"
        :disabled="loading"
        @input="handleRecoveryInput"
      />
    </div>

    <button
      type="submit"
      class="btn btn-primary login-btn"
      :disabled="loading || !recoveryCode"
    >
      <span v-if="loading" class="spinner"></span>
      <span>{{ loading ? 'Verifying...' : 'Verify Recovery Code' }}</span>
    </button>

    <div class="auth-switch-links">
      <button type="button" class="text-link-btn" @click="$emit('switchToTotp')">
        🔐 Use Authenticator App
      </button>
      <button type="button" class="text-link-btn back-btn" @click="$emit('back')">
        ← Back to Sign In
      </button>
    </div>
  </form>
</template>

<script setup lang="ts">
import { ref, onMounted, watch, nextTick } from 'vue'

const props = defineProps<{
  mode: 'totp' | 'recovery'
  totpCode: string
  recoveryCode: string
  loading?: boolean
}>()

const emit = defineEmits<{
  (e: 'update:totpCode', value: string): void
  (e: 'update:recoveryCode', value: string): void
  (e: 'submitTotp'): void
  (e: 'submitRecovery'): void
  (e: 'switchToRecovery'): void
  (e: 'switchToTotp'): void
  (e: 'back'): void
  (e: 'totpInput', event: Event): void
}>()

const totpInput = ref<HTMLInputElement | null>(null)
const recoveryInput = ref<HTMLInputElement | null>(null)

onMounted(() => {
  if (props.mode === 'totp') {
    totpInput.value?.focus()
  } else if (props.mode === 'recovery') {
    recoveryInput.value?.focus()
  }
})

watch(
  () => props.mode,
  async (newMode) => {
    await nextTick()
    if (newMode === 'totp') {
      totpInput.value?.focus()
    } else if (newMode === 'recovery') {
      recoveryInput.value?.focus()
    }
  }
)

function handleTotpInput(e: Event) {
  emit('totpInput', e)
}

function handleRecoveryInput(e: Event) {
  const target = e.target as HTMLInputElement
  const clean = target.value.toUpperCase().trim()
  emit('update:recoveryCode', clean)
}
</script>
