/**
 * GitOps Control Plane — Patch generator, PR preview, PR status dashboard, approval flow.
 * P4-001 through P4-004 combined.
 */
(function (global) {
  'use strict';

  var gitopsPRs = [];
  var gitopsApprovals = [];

  function init() {
    var generateBtn = document.getElementById('gitops-generate');
    if (generateBtn) generateBtn.addEventListener('click', generatePatch);

    loadRealData();
  }

  function loadRealData() {
    fetchPRs();
    fetchApprovals();
  }

  function fetchPRs() {
    APIClient.get('/prs')
      .then(function(json) {
        gitopsPRs = json.data || [];
        renderPRs();
      })
      .catch(function(err) {
        console.error('Error fetching PRs:', err);
        var body = document.getElementById('gitops-pr-body');
        if (body) {
          body.innerHTML = '<tr><td colspan="7" class="text-center" style="color:var(--color-muted);padding:24px;">Failed to load pull requests: ' + esc(err.message) + '</td></tr>';
        }
      });
  }

  function fetchApprovals() {
    APIClient.get('/promotions')
      .then(function(json) {
        gitopsApprovals = json.data || json || [];
        renderApprovals();
      })
      .catch(function(err) {
        console.error('Error fetching promotions:', err);
        var body = document.getElementById('gitops-approval-body');
        if (body) {
          body.innerHTML = '<tr><td colspan="6" class="text-center" style="color:var(--color-muted);padding:24px;">Failed to load promotion requests: ' + esc(err.message) + '</td></tr>';
        }
      });
  }

  function generatePatch() {
    var type = document.getElementById('gitops-patch-type');
    var target = document.getElementById('gitops-target');
    var desc = document.getElementById('gitops-description');
    var btn = document.getElementById('gitops-generate');

    var patchType = type ? type.value : 'helm';
    var targetName = target ? target.value.trim() : '';
    var description = desc ? desc.value.trim() : '';

    if (!targetName) { if (target) target.style.borderColor = 'var(--color-trading-down)'; return; }
    if (target) target.style.borderColor = '';

    btn.textContent = '⏳ Generating...';
    btn.disabled = true;

    setTimeout(function () {
      var patch = generatePatchContent(patchType, targetName, description);
      renderPRPreview(patchType, targetName, description, patch);
      btn.textContent = '🔧 Generate';
      btn.disabled = false;

      AppState.addAuditLog({ action: 'gitops-patch', target: targetName, result: 'success' });
    }, 1500);
  }

  function generatePatchContent(type, target, desc) {
    switch (type) {
      case 'helm':
        return '# values.yaml patch for ' + target + '\n' +
          '# ' + (desc || 'Auto-generated by AI agent') + '\n\n' +
          target.replace(/[^a-z0-9]/gi, '') + ':\n' +
          '  replicaCount: 3\n' +
          '  resources:\n' +
          '    limits:\n' +
          '      cpu: "1"\n' +
          '      memory: "1Gi"\n' +
          '    requests:\n' +
          '      cpu: "500m"\n' +
          '      memory: "512Mi"\n' +
          '  autoscaling:\n' +
          '    enabled: true\n' +
          '    minReplicas: 2\n' +
          '    maxReplicas: 10\n' +
          '    targetCPUUtilization: 80';
      case 'kustomize':
        return '# kustomization.yaml patch\n' +
          'apiVersion: kustomize.config.k8s.io/v1beta1\n' +
          'kind: Kustomization\n\n' +
          'patchesStrategicMerge:\n' +
          '- |-\n' +
          '  apiVersion: apps/v1\n' +
          '  kind: Deployment\n' +
          '  metadata:\n' +
          '    name: ' + target + '\n' +
          '  spec:\n' +
          '    template:\n' +
          '      spec:\n' +
          '        containers:\n' +
          '        - name: app\n' +
          '          resources:\n' +
          '            limits:\n' +
          '              memory: "1Gi"';
      default:
        return 'apiVersion: apps/v1\n' +
          'kind: Deployment\n' +
          'metadata:\n' +
          '  name: ' + target + '\n' +
          'spec:\n' +
          '  replicas: 3\n' +
          '  template:\n' +
          '    spec:\n' +
          '      containers:\n' +
          '      - name: app\n' +
          '        resources:\n' +
          '          limits:\n' +
          '            memory: "1Gi"\n' +
          '            cpu: "1"';
    }
  }

  function renderPRPreview(type, target, desc, patch) {
    var body = document.getElementById('gitops-pr-preview');
    if (!body) return;
    var branchName = 'fix/' + target.replace(/[^a-z0-9]/gi, '-').toLowerCase() + '-' + Date.now().toString(36);
    body.innerHTML =
      '<div class="pipeline-detail" style="margin-bottom:var(--space-sm);">' +
        '<div class="pipeline-detail-row"><span class="pipeline-detail-label">Branch</span><span class="pipeline-detail-value"><code style="font-size:12px;color:var(--color-primary);">' + esc(branchName) + '</code></span></div>' +
        '<div class="pipeline-detail-row"><span class="pipeline-detail-label">Commit</span><span class="pipeline-detail-value">fix(' + esc(target) + '): ' + esc(desc || 'auto-remediation') + '</span></div>' +
        '<div class="pipeline-detail-row"><span class="pipeline-detail-label">Type</span><span class="pipeline-detail-value"><span class="badge badge-synced">' + esc(type) + '</span></span></div>' +
        '<div class="pipeline-detail-row"><span class="pipeline-detail-label">Files Changed</span><span class="pipeline-detail-value">1 file (+12, -3)</span></div>' +
      '</div>' +
      '<label class="form-label">Diff Preview</label>' +
      '<pre class="ai-test-response" style="font-size:12px;max-height:200px;overflow-y:auto;">' + esc(patch) + '</pre>' +
      '<div style="display:flex;gap:var(--space-xs);margin-top:var(--space-sm);">' +
        '<button class="btn btn-primary btn-sm" id="btn-create-pr-action">🔀 Create PR</button>' +
        '<button class="btn btn-ghost btn-sm" onclick="alert(\'Rollback plan generated\')">⏪ Rollback Plan</button>' +
      '</div>';

    var createPrBtn = document.getElementById('btn-create-pr-action');
    if (createPrBtn) {
      createPrBtn.addEventListener('click', function() {
        createPR({
          branch: branchName,
          title: 'fix(' + target + '): ' + (desc || 'auto-remediation'),
          description: desc || 'Auto-generated patch for ' + target,
          repo_url: 'https://github.com/k8s-selfhost-agent/manifests',
          provider: 'github',
          files_changed: [{
            path: type === 'helm' ? 'values.yaml' : (type === 'kustomize' ? 'kustomization.yaml' : 'deployment.yaml'),
            content: patch,
            action: 'modify'
          }]
        });
      });
    }
  }

  function createPR(payload) {
    var btn = document.getElementById('btn-create-pr-action');
    if (btn) {
      btn.textContent = '⏳ Creating...';
      btn.disabled = true;
    }
    APIClient.post('/prs', payload)
    .then(function(data) {
      alert('PR created successfully!');
      fetchPRs();
      var preview = document.getElementById('gitops-pr-preview');
      if (preview) preview.innerHTML = '<div class="text-center" style="padding:var(--space-md);color:var(--color-muted);">Generate a patch to preview changes.</div>';
    })
    .catch(function(err) {
      alert('Error creating PR: ' + err.message);
      if (btn) {
        btn.textContent = '🔀 Create PR';
        btn.disabled = false;
      }
    });
  }

  function renderPRs() {
    var body = document.getElementById('gitops-pr-body');
    if (!body) return;
    body.innerHTML = '';
    if (gitopsPRs.length === 0) {
      body.innerHTML = '<tr><td colspan="7" class="text-center" style="color:var(--color-muted);padding:24px;">No active pull requests found.</td></tr>';
      return;
    }
    gitopsPRs.forEach(function (pr) {
      var tr = document.createElement('tr');
      var status = pr.Status || pr.status;
      tr.innerHTML =
        '<td><strong style="color:var(--color-primary);">' + esc(pr.ID || pr.id) + '</strong></td>' +
        '<td><code style="font-size:12px;">' + esc(pr.Branch || pr.branch) + '</code></td>' +
        '<td>' + esc(pr.RepoURL || pr.repo_url || pr.target) + '</td>' +
        '<td>' + prStatusBadge(status) + '</td>' +
        '<td>' + esc(pr.Provider || pr.provider || 'github') + '</td>' +
        '<td style="font-size:12px;color:var(--color-muted);">' + esc(pr.CreatedAt ? new Date(pr.CreatedAt).toLocaleDateString() : (pr.created || '')) + '</td>' +
        '<td><div class="action-group">' +
          (status === 'open' ?
            '<button class="action-btn" onclick="GitOpsSection.mergePR(\'' + (pr.ID || pr.id) + '\')">Merge</button>' +
            '<button class="action-btn danger" onclick="GitOpsSection.closePR(\'' + (pr.ID || pr.id) + '\')">Close</button>' :
            '<button class="action-btn">View</button>') +
        '</div></td>';
      body.appendChild(tr);
    });
  }

  function mergePR(id) {
    APIClient.post('/prs/' + id + '/merge')
    .then(function() {
      fetchPRs();
    })
    .catch(function(err) {
      alert('Error merging PR: ' + err.message);
    });
  }

  function closePR(id) {
    APIClient.post('/prs/' + id + '/close')
    .then(function() {
      fetchPRs();
    })
    .catch(function(err) {
      alert('Error closing PR: ' + err.message);
    });
  }

  function renderApprovals() {
    var body = document.getElementById('gitops-approval-body');
    if (!body) return;
    body.innerHTML = '';
    if (gitopsApprovals.length === 0) {
      body.innerHTML = '<tr><td colspan="6" class="text-center" style="color:var(--color-muted);padding:24px;">No promotion actions required.</td></tr>';
      return;
    }
    gitopsApprovals.forEach(function (a) {
      var tr = document.createElement('tr');
      tr.innerHTML =
        '<td><strong>' + esc(a.Service || a.service) + '</strong></td>' +
        '<td><span class="badge badge-synced">' + esc(a.ToEnv || a.to_env || a.env) + '</span></td>' +
        '<td><code style="font-size:12px;">' + esc(a.Version || a.version) + '</code></td>' +
        '<td>' + approvalBadge(a.Status || a.status) + '</td>' +
        '<td>' + esc(a.Requester || a.requester || a.requestedBy) + '</td>' +
        '<td><div class="action-group">' +
          ((a.Status || a.status) === 'pending' ?
            '<button class="action-btn" style="color:var(--color-trading-up);" onclick="GitOpsSection.approvePromotion(\'' + a.id + '\')">Approve</button>' +
            '<button class="action-btn danger" onclick="GitOpsSection.rejectPromotion(\'' + a.id + '\')">Reject</button>' :
            '<button class="action-btn">Details</button>') +
        '</div></td>';
      body.appendChild(tr);
    });
  }

  function approvePromotion(id) {
    APIClient.put('/promotions/' + id + '/approve?approver=admin')
    .then(function() {
      fetchApprovals();
    })
    .catch(function(err) {
      alert('Error approving promotion: ' + err.message);
    });
  }

  function rejectPromotion(id) {
    APIClient.put('/promotions/' + id + '/reject?rejecter=admin')
    .then(function() {
      fetchApprovals();
    })
    .catch(function(err) {
      alert('Error rejecting promotion: ' + err.message);
    });
  }

  function prStatusBadge(s) {
    if (s === 'open') return '<span class="badge badge-degraded">● Open</span>';
    if (s === 'merged') return '<span class="badge badge-healthy">✓ Merged</span>';
    return '<span class="badge badge-down">✗ Failed</span>';
  }

  function approvalBadge(s) {
    if (s === 'pending') return '<span class="badge badge-degraded">⏳ Pending</span>';
    if (s === 'approved') return '<span class="badge badge-healthy">✓ Approved</span>';
    return '<span class="badge badge-down">✗ Rejected</span>';
  }

  global.GitOpsSection = {
    init: init,
    mergePR: mergePR,
    closePR: closePR,
    approvePromotion: approvePromotion,
    rejectPromotion: rejectPromotion
  };
})(window);
