/**
 * GitOps Control Plane — Patch generator, PR preview, PR status dashboard, approval flow.
 * P4-001 through P4-004 combined.
 */
(function (global) {
  'use strict';

  var mockPRs = [
    { id: '#142', branch: 'fix/memory-limit-increase', target: 'payment-svc', status: 'open', author: 'ai-agent', created: '2m ago' },
    { id: '#141', branch: 'fix/hpa-config', target: 'api-server', status: 'merged', author: 'sre-bot', created: '1h ago' },
    { id: '#140', branch: 'fix/image-rollback', target: 'frontend', status: 'merged', author: 'admin', created: '3h ago' },
    { id: '#139', branch: 'feat/resource-quotas', target: 'namespace/production', status: 'failed', author: 'ai-agent', created: '5h ago' },
  ];

  var mockApprovals = [
    { deployment: 'payment-svc', env: 'production', version: 'v2.5.0', status: 'pending', requestedBy: 'ai-agent' },
    { deployment: 'api-server', env: 'staging', version: 'v3.1.2', status: 'approved', requestedBy: 'admin' },
    { deployment: 'frontend', env: 'production', version: 'v1.8.0', status: 'rejected', requestedBy: 'sre-bot' },
  ];

  function init() {
    var generateBtn = document.getElementById('gitops-generate');
    if (generateBtn) generateBtn.addEventListener('click', generatePatch);

    loadMockData();
  }

  function loadMockData() {
    renderPRs();
    renderApprovals();
  }

  function generatePatch() {
    var type = document.getElementById('gitops-patch-type');
    var target = document.getElementById('gitops-target');
    var desc = document.getElementById('gitops-description');
    var btn = document.getElementById('gitops-generate');

    var patchType = type ? type.value : 'helm';
    var targetName = target ? target.value.trim() : '';
    var description = desc ? desc.value.trim() : '';

    if (!targetName) { if (target) target.style.borderColor = 'var(--color-trading-down)'; return; }
    if (target) target.style.borderColor = '';

    btn.textContent = '⏳ Generating...';
    btn.disabled = true;

    setTimeout(function () {
      var patch = generatePatchContent(patchType, targetName, description);
      renderPRPreview(patchType, targetName, description, patch);
      btn.textContent = '🔧 Generate';
      btn.disabled = false;

      // Add to PR list
      mockPRs.unshift({
        id: '#' + (143 + Math.floor(Math.random() * 100)),
        branch: 'fix/' + targetName.replace(/[^a-z0-9]/gi, '-').toLowerCase(),
        target: targetName,
        status: 'open',
        author: 'ai-agent',
        created: 'just now'
      });
      renderPRs();
      AppState.addAuditLog({ action: 'gitops-patch', target: targetName, result: 'success' });
    }, 1500);
  }

  function generatePatchContent(type, target, desc) {
    switch (type) {
      case 'helm':
        return '# values.yaml patch for ' + target + '\n' +
          '# ' + (desc || 'Auto-generated by AI agent') + '\n\n' +
          target.replace(/[^a-z0-9]/gi, '') + ':\n' +
          '  replicaCount: 3\n' +
          '  resources:\n' +
          '    limits:\n' +
          '      cpu: "1"\n' +
          '      memory: "1Gi"\n' +
          '    requests:\n' +
          '      cpu: "500m"\n' +
          '      memory: "512Mi"\n' +
          '  autoscaling:\n' +
          '    enabled: true\n' +
          '    minReplicas: 2\n' +
          '    maxReplicas: 10\n' +
          '    targetCPUUtilization: 80';
      case 'kustomize':
        return '# kustomization.yaml patch\n' +
          'apiVersion: kustomize.config.k8s.io/v1beta1\n' +
          'kind: Kustomization\n\n' +
          'patchesStrategicMerge:\n' +
          '- |-\n' +
          '  apiVersion: apps/v1\n' +
          '  kind: Deployment\n' +
          '  metadata:\n' +
          '    name: ' + target + '\n' +
          '  spec:\n' +
          '    template:\n' +
          '      spec:\n' +
          '        containers:\n' +
          '        - name: app\n' +
          '          resources:\n' +
          '            limits:\n' +
          '              memory: "1Gi"';
      default:
        return 'apiVersion: apps/v1\n' +
          'kind: Deployment\n' +
          'metadata:\n' +
          '  name: ' + target + '\n' +
          'spec:\n' +
          '  replicas: 3\n' +
          '  template:\n' +
          '    spec:\n' +
          '      containers:\n' +
          '      - name: app\n' +
          '        resources:\n' +
          '          limits:\n' +
          '            memory: "1Gi"\n' +
          '            cpu: "1"';
    }
  }

  function renderPRPreview(type, target, desc, patch) {
    var body = document.getElementById('gitops-pr-preview');
    if (!body) return;
    var branchName = 'fix/' + target.replace(/[^a-z0-9]/gi, '-').toLowerCase() + '-' + Date.now().toString(36);
    body.innerHTML =
      '<div class="pipeline-detail" style="margin-bottom:var(--space-sm);">' +
        '<div class="pipeline-detail-row"><span class="pipeline-detail-label">Branch</span><span class="pipeline-detail-value"><code style="font-size:12px;color:var(--color-primary);">' + esc(branchName) + '</code></span></div>' +
        '<div class="pipeline-detail-row"><span class="pipeline-detail-label">Commit</span><span class="pipeline-detail-value">fix(' + esc(target) + '): ' + esc(desc || 'auto-remediation') + '</span></div>' +
        '<div class="pipeline-detail-row"><span class="pipeline-detail-label">Type</span><span class="pipeline-detail-value"><span class="badge badge-synced">' + esc(type) + '</span></span></div>' +
        '<div class="pipeline-detail-row"><span class="pipeline-detail-label">Files Changed</span><span class="pipeline-detail-value">1 file (+12, -3)</span></div>' +
      '</div>' +
      '<label class="form-label">Diff Preview</label>' +
      '<pre class="ai-test-response" style="font-size:12px;max-height:200px;overflow-y:auto;">' + esc(patch) + '</pre>' +
      '<div style="display:flex;gap:var(--space-xs);margin-top:var(--space-sm);">' +
        '<button class="btn btn-primary btn-sm" onclick="alert(\'PR created successfully!\')">🔀 Create PR</button>' +
        '<button class="btn btn-ghost btn-sm" onclick="alert(\'Rollback plan generated\')">⏪ Rollback Plan</button>' +
      '</div>';
  }

  function renderPRs() {
    var body = document.getElementById('gitops-pr-body');
    if (!body) return;
    body.innerHTML = '';
    mockPRs.forEach(function (pr) {
      var tr = document.createElement('tr');
      tr.innerHTML =
        '<td><strong style="color:var(--color-primary);">' + esc(pr.id) + '</strong></td>' +
        '<td><code style="font-size:12px;">' + esc(pr.branch) + '</code></td>' +
        '<td>' + esc(pr.target) + '</td>' +
        '<td>' + prStatusBadge(pr.status) + '</td>' +
        '<td>' + esc(pr.author) + '</td>' +
        '<td style="font-size:12px;color:var(--color-muted);">' + esc(pr.created) + '</td>' +
        '<td><div class="action-group">' +
          (pr.status === 'open' ? '<button class="action-btn">Merge</button><button class="action-btn">Close</button>' : '<button class="action-btn">View</button>') +
        '</div></td>';
      body.appendChild(tr);
    });
  }

  function renderApprovals() {
    var body = document.getElementById('gitops-approval-body');
    if (!body) return;
    body.innerHTML = '';
    mockApprovals.forEach(function (a) {
      var tr = document.createElement('tr');
      tr.innerHTML =
        '<td><strong>' + esc(a.deployment) + '</strong></td>' +
        '<td><span class="badge badge-synced">' + esc(a.env) + '</span></td>' +
        '<td><code style="font-size:12px;">' + esc(a.version) + '</code></td>' +
        '<td>' + approvalBadge(a.status) + '</td>' +
        '<td>' + esc(a.requestedBy) + '</td>' +
        '<td><div class="action-group">' +
          (a.status === 'pending' ?
            '<button class="action-btn" style="color:var(--color-trading-up);">Approve</button>' +
            '<button class="action-btn danger">Reject</button>' :
            '<button class="action-btn">Details</button>') +
        '</div></td>';
      body.appendChild(tr);
    });
  }

  function prStatusBadge(s) {
    if (s === 'open') return '<span class="badge badge-degraded">● Open</span>';
    if (s === 'merged') return '<span class="badge badge-healthy">✓ Merged</span>';
    return '<span class="badge badge-down">✗ Failed</span>';
  }

  function approvalBadge(s) {
    if (s === 'pending') return '<span class="badge badge-degraded">⏳ Pending</span>';
    if (s === 'approved') return '<span class="badge badge-healthy">✓ Approved</span>';
    return '<span class="badge badge-down">✗ Rejected</span>';
  }

  

  global.GitOpsSection = { init: init };
})(window);
